<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ServiceTemplate.DataAccess</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Toolbelt.EntityFrameworkCore.IndexAttribute" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Context\ModelsConfiguration\" />
        <Folder Include="Interfaces\" />
        <Folder Include="Migrations\SQL\" />
        <Folder Include="Models\" />
    </ItemGroup>

</Project>
